apiVersion: v1

kind: Service

metadata:

  name: mongodb-kubernetes

  labels:

    app: mongodb-kubernetes

spec:

  selector:

    app: mongodb-kubernetes

  ports:

  - port: 27017

    targetPort: 27017

    nodePort: 30003

  type: NodePort
